### ISSUE TITLE
All videos randomly stop working

### ISSUE THREAD

**Issue by mav808** [mauriceoegerli/viewtube-vue#2952]
### Describe the Bug

Somewhat randomly, I get a video playback error. This can happen when starting a video or while a video is playing. Once the error occurs, no more videos will play until the Viewtube instance is restarted. Once restarted, videos will play again for a while until again the error occurs. The longest without an error has been about 6 hours, but it usually much sooner.

The popup with the error reads...

Video playback error
PIPELINE_LOAD_ERROR: An HTTP status code indicating failure was received: 403

### Steps to Reproduce the Bug

1. Use ViewTube as normal
2. At some point within about 6 hours, but sometimes much sooner, videos will stop playing and the error is displayed.
3. ViewTube must be restarted and then videos start working again.

### Expected Behaviour

Videos should keep playing.

### Screenshot/Screen recording

<img width="438" alt="Screenshot 2024-07-24 at 19 40 31" src="https://github.com/user-attachments/assets/3563a0a2-8e94-4004-9b77-719d68657986">

### Device Info

- Device: M2 MacBook Air
- OS: macOS 14.5
- Browser: Safari

### Additional Context

Self-hosted ViewTube running in a Docker container.

**Comment by ac1mx** [comment]
This has also appeared for me just recently.

**Comment by Berkopl** [comment]
Same for me Video playback error
PIPELINE_LOAD_ERROR: An HTTP status code indicating failure was received: 403

what is Happening YouTube Google star war for $$$ with ViewTube?

**Comment by ac1mx** [comment]
Looks like [https://github.com/TeamNewPipe/NewPipe/issues/11255#issue-2398629565](url) was fixed by the NewPipe team, seems to be the same error.

**Comment by XfEnE** [comment]
having same issue for a while now :(

**Comment by Berkopl** [comment]
Any solution?!

**Comment by Berkopl** [comment]
> Looks like [https://github.com/TeamNewPipe/NewPipe/issues/11255#issue-2398629565](url) was fixed by the NewPipe team, seems to be the same error.

Sorry don't se solution!

**Comment by jakejackson** [comment]
> > Looks like [https://github.com/TeamNewPipe/NewPipe/issues/11255#issue-2398629565](url) was fixed by the NewPipe team, seems to be the same error.
> 
> Sorry don't se solution!

If I'm correctly following, from the NewPipe issue linked by ac1mx: [https://github.com/TeamNewPipe/NewPipe/issues/11255](url), Stypox seems to indicate [https://github.com/TeamNewPipe/NewPipe/issues/11255#issuecomment-2223964100](url) that the issue was fixed [https://github.com/TeamNewPipe/NewPipeExtractor/pull/1191](url) and that a hotfix release is in the making.

That said, I suppose we'll simply need to patiently wait for fix(es) to be merged into ViewTube branches -- like (I assume) most self-hosters, I'm running the dev branch to work around the "Unexpected token (1:47)" error [https://github.com/ViewTube/viewtube/issues/2929](url), but the PIPELINE_LOAD_ERROR unfortunately hasn't been fixed yet in dev (or, obviously, latest.)

**Comment by Berkopl** [comment]
> > > Looks like [https://github.com/TeamNewPipe/NewPipe/issues/11255#issue-2398629565](url) was fixed by the NewPipe team, seems to be the same error.
> > 
> > 
> > Sorry don't se solution!
> 
> If I'm correctly following, from the NewPipe issue linked by ac1mx: [https://github.com/TeamNewPipe/NewPipe/issues/11255](url), Stypox seems to indicate [https://github.com/TeamNewPipe/NewPipe/issues/11255#issuecomment-2223964100](url) that the issue was fixed [https://github.com/TeamNewPipe/NewPipeExtractor/pull/1191](url) and that a hotfix release is in the making.
> 
> That said, I suppose we'll simply need to patiently wait for fix(es) to be merged into ViewTube branches -- like (I assume) most self-hosters, I'm running the dev branch to work around the "Unexpected token (1:47)" error [https://github.com/ViewTube/viewtube/issues/2929](url), but the PIPELINE_LOAD_ERROR unfortunately hasn't been fixed yet in dev (or, obviously, latest.)

ok, so we wait. Please set us know wen we can update viewtube. Thx

**Comment by Berkopl** [comment]
PS. ist there viewtube alternative on docker?

**Comment by ac1mx** [comment]
Still appearing, although typically the video gets to around 20 seconds before the error appears.

**Comment by lersi** [comment]
~~I also have this issue, it seems that all stable releases are broken, probably because google changed something.
I have just ran a nightly build and it seems to work fine. maybe the dev version also works but I did not try it~~

The stable versions do not work at all, no able to play any video.
The nighly build worked for the first and second video, afterwards it does the same and stops working 30 seconds into the video. This is probably google's actions against "pirates" (people who want good experience on the platform)

**Comment by ac1mx** [comment]
If you could try the dev build that would be great.


________________________________

**Comment by ac1mx** [comment]
Invidious has this fixed btw. I hope Viewtube can be updated with the same fix soon, I much prefer the Viewtube UI.

**Comment by iwannet** [comment]
is this the cause ? https://github.com/LuanRT/YouTube.js/issues/724

**Comment by alienbob** [comment]
I experience the same issue. I run viewtube in Docker, latest version of viewtube obtained from Docker Hub (0.17.0).
For me this error appears when video's have barely started, like 10 or 20 seconds into the playback.

**Comment by NovaCyntax** [comment]
Haven't been able to use Viewtube all summer because of this issue, probably going to have to stand up an Invidious instance in the meantime. I wish I could document or debug more but it looks like everything's been mentioned already

**Comment by skynet2982** [comment]
Same here

**Comment by averagenokiauser** [comment]
I am also getting this error. I am self hosting it on Raspberry Pi 4.

**Comment by LeMaX10** [comment]
I also get this error. I instance in docker, but this error is also on https://viewtube.io / official copy :(

**Comment by LeMaX10** [comment]
I found the cause of the bug. An external Youtube.js >=10.4.0 fixed it, viewtube hasn't held it yet, but version updated in development branch.
The reason is the absence of po_token and visitor_data in the request.

See - https://github.com/LuanRT/YouTube.js/issues/728#issuecomment-2306525195

To generate those you can use https://github.com/iv-org/youtube-trusted-session-generator
And add po_token, visitor_data to this file https://github.com/ViewTube/viewtube/blob/development/server/src/common/innertube/innertube.ts

Add po_token and vistor_data after line 17 example: 
```
const innertubeOptions: InnerTubeConfig = {
  cache: new UniversalCache(true, cacheDirectory),
  fetch: innertubeFetch,
  enable_session_cache: false,
  lang: 'en',
  po_token: "AddYouPoTokenString",
  visitor_data: "AddYouVisitorDataString",
};
```

[Not working in stable version, only dev or nightly version]

**Comment by odd-orca** [comment]
> I found the cause of the bug. An external Youtube.js >=10.4.0 fixed it, viewtube hasn't held it yet, but version updated in development branch. The reason is the absence of po_token and visitor_data in the request.
> 
> See - [LuanRT/YouTube.js#728 (comment)](https://github.com/LuanRT/YouTube.js/issues/728#issuecomment-2306525195)
> 
> To generate those you can use https://github.com/iv-org/youtube-trusted-session-generator And add po_token, visitor_data to this file https://github.com/ViewTube/viewtube/blob/development/server/src/common/innertube/innertube.ts
> 
> Add po_token and vistor_data after line 17 example:
> 
> ```
> const innertubeOptions: InnerTubeConfig = {
>   cache: new UniversalCache(true, cacheDirectory),
>   fetch: innertubeFetch,
>   enable_session_cache: false,
>   lang: 'en',
>   po_token: "AddYouPoTokenString",
>   visitor_data: "AddYouVisitorDataString",
> };
> ```
> 
> [Not working in stable version, only dev or nightly version]

I didn't manage to make it work:

```
SyntaxError: Unexpected identifier 'po_token'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/app/server/dist/core/comments/comments.service.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.17.0
``` 

am I missing something? 

Build is Dev - running on unraid.

**Comment by LeMaX10** [comment]
> I didn't manage to make it work:

screenshot please? 

My screenshot:
<img width="1373" alt="Снимок экрана 2024-09-27 в 22 17 01" src="https://github.com/user-attachments/assets/4e72ff8a-539d-4e65-9536-4c8d61b6e7ec">

**Comment by odd-orca** [comment]
> > I didn't manage to make it work:
> 
> screenshot please?
> 
> My screenshot: <img alt="Снимок экрана 2024-09-27 в 22 17 01" width="1373" src="https://private-user-images.githubusercontent.com/10564391/371653085-4e72ff8a-539d-4e65-9536-4c8d61b6e7ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTI0OTcsIm5iZiI6MTcyNzUxMjE5NywicGF0aCI6Ii8xMDU2NDM5MS8zNzE2NTMwODUtNGU3MmZmOGEtNTM5ZC00ZTY1LTk1MzYtNGM4ZDYxYjZlN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA4Mjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjEwMWY5MTk3MWU3NDZmM2JjZjFlNjFjZmExYzE5MmNhM2EzODM0ZmY0MzFjM2U1M2M1ZTE5ZmU4NTA1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5AO0Md5ixqBkhwi-5OlqJKycdUwBM6GWhiUXQP7BECY">


![2024-09-28_10-31](https://github.com/user-attachments/assets/53272943-2045-4c37-b99b-8a357a3b8e72)
![2024-09-28_10-28](https://github.com/user-attachments/assets/a3b84eac-594f-426c-a564-67ca865f8436)
![2024-09-28_10-24](https://github.com/user-attachments/assets/29d37da7-014f-430e-9f99-caf499c9f87b)

I generated the token with the invidious script.

**Comment by LeMaX10** [comment]
> > > I didn't manage to make it work:
> 
> > 
> 
> > screenshot please?
> 
> > 
> 
> > My screenshot: <img alt="Снимок экрана 2024-09-27 в 22 17 01" width="1373" src="https://private-user-images.githubusercontent.com/10564391/371653085-4e72ff8a-539d-4e65-9536-4c8d61b6e7ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTI0OTcsIm5iZiI6MTcyNzUxMjE5NywicGF0aCI6Ii8xMDU2NDM5MS8zNzE2NTMwODUtNGU3MmZmOGEtNTM5ZC00ZTY1LTk1MzYtNGM4ZDYxYjZlN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA4Mjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjEwMWY5MTk3MWU3NDZmM2JjZjFlNjFjZmExYzE5MmNhM2EzODM0ZmY0MzFjM2U1M2M1ZTE5ZmU4NTA1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5AO0Md5ixqBkhwi-5OlqJKycdUwBM6GWhiUXQP7BECY">
> 
> 
> 
> 
> 
> ![2024-09-28_10-31](https://github.com/user-attachments/assets/53272943-2045-4c37-b99b-8a357a3b8e72)
> 
> ![2024-09-28_10-28](https://github.com/user-attachments/assets/a3b84eac-594f-426c-a564-67ca865f8436)
> 
> ![2024-09-28_10-24](https://github.com/user-attachments/assets/29d37da7-014f-430e-9f99-caf499c9f87b)
> 
> 
> 
> I generated the token with the invidious script.
> 
> 

You missing comma after - lang: 'en'
it should be like this: _lang: 'en'**,**_

**Comment by odd-orca** [comment]
You were right! Instance starts with the tokens but i stell get the error:

![2024-09-28_11-00](https://github.com/user-attachments/assets/b05049ba-c2ab-4847-a13d-69db129410d3)

But thanks anyway!

**Comment by LeMaX10** [comment]
> You were right! Instance starts with the tokens but i stell get the error:
> 
> 
> 
> ![2024-09-28_11-00](https://github.com/user-attachments/assets/b05049ba-c2ab-4847-a13d-69db129410d3)
> 
> 
> 
> But thanks anyway!

maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.

**Comment by odd-orca** [comment]
> > You were right! Instance starts with the tokens but i stell get the error:
> > ![2024-09-28_11-00](https://private-user-images.githubusercontent.com/99789354/371744363-b05049ba-c2ab-4847-a13d-69db129410d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ1OTAsIm5iZiI6MTcyNzUxNDI5MCwicGF0aCI6Ii85OTc4OTM1NC8zNzE3NDQzNjMtYjA1MDQ5YmEtYzJhYi00ODQ3LWExM2QtNjlkYjEyOTQxMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTU3MGZmNTdlZWJhZjM1NjA2ZmY3NTNmZWU1YTJhODVkMmQ2YzQ2N2RmMzdkYjM4MWJkYmJkZWY4ZWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMq6oa7sho7dlLt4CLT3wLLRBvq8Yzl1ALKzz3ev-bo)
> > But thanks anyway!
> 
> maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.

I did so too, multiple times, with redis and mongo as well, tried serveral videos etc. - no such luck.

**Comment by LeMaX10** [comment]
> > > You were right! Instance starts with the tokens but i stell get the error:
> 
> > > ![2024-09-28_11-00](https://private-user-images.githubusercontent.com/99789354/371744363-b05049ba-c2ab-4847-a13d-69db129410d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ1OTAsIm5iZiI6MTcyNzUxNDI5MCwicGF0aCI6Ii85OTc4OTM1NC8zNzE3NDQzNjMtYjA1MDQ5YmEtYzJhYi00ODQ3LWExM2QtNjlkYjEyOTQxMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTU3MGZmNTdlZWJhZjM1NjA2ZmY3NTNmZWU1YTJhODVkMmQ2YzQ2N2RmMzdkYjM4MWJkYmJkZWY4ZWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMq6oa7sho7dlLt4CLT3wLLRBvq8Yzl1ALKzz3ev-bo)
> 
> > > But thanks anyway!
> 
> > 
> 
> > maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.
> 
> 
> 
> I did so too, multiple times, with redis and mongo as well, tried serveral videos etc. - no such luck.

You version youtubei.js 10.4.0 ?
See in server/packages.json
And see server/node_modules/youtubei.js/packages.json first or two line "version: "10.4.0"

**Comment by odd-orca** [comment]
> > > > You were right! Instance starts with the tokens but i stell get the error:
> > 
> > 
> > > > ![2024-09-28_11-00](https://private-user-images.githubusercontent.com/99789354/371744363-b05049ba-c2ab-4847-a13d-69db129410d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ1OTAsIm5iZiI6MTcyNzUxNDI5MCwicGF0aCI6Ii85OTc4OTM1NC8zNzE3NDQzNjMtYjA1MDQ5YmEtYzJhYi00ODQ3LWExM2QtNjlkYjEyOTQxMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTU3MGZmNTdlZWJhZjM1NjA2ZmY3NTNmZWU1YTJhODVkMmQ2YzQ2N2RmMzdkYjM4MWJkYmJkZWY4ZWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMq6oa7sho7dlLt4CLT3wLLRBvq8Yzl1ALKzz3ev-bo)
> > 
> > 
> > > > But thanks anyway!
> > 
> > 
> > > 
> > 
> > 
> > > maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.
> > 
> > 
> > I did so too, multiple times, with redis and mongo as well, tried serveral videos etc. - no such luck.
> 
> You version youtubei.js 10.4.0 ? See in server/packages.json And see server/node_modules/youtubei.js/packages.json first or two line "version: "10.4.0"

Yes, I checked both locations:

``` 
root@19a445b424e5:/home/app/server/node_modules/youtubei.js# cat package.json | grep version
  "version": "10.4.0",
``` 

``` 
root@19a445b424e5:/home/app/server# cat package.json | grep youtube
    "youtubei.js": "10.4.0",
```

**Comment by LeMaX10** [comment]
> > > > > You were right! Instance starts with the tokens but i stell get the error:
> > > 
> > > 
> > > > > ![2024-09-28_11-00](https://private-user-images.githubusercontent.com/99789354/371744363-b05049ba-c2ab-4847-a13d-69db129410d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ1OTAsIm5iZiI6MTcyNzUxNDI5MCwicGF0aCI6Ii85OTc4OTM1NC8zNzE3NDQzNjMtYjA1MDQ5YmEtYzJhYi00ODQ3LWExM2QtNjlkYjEyOTQxMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTU3MGZmNTdlZWJhZjM1NjA2ZmY3NTNmZWU1YTJhODVkMmQ2YzQ2N2RmMzdkYjM4MWJkYmJkZWY4ZWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMq6oa7sho7dlLt4CLT3wLLRBvq8Yzl1ALKzz3ev-bo)
> > > 
> > > 
> > > > > But thanks anyway!
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.
> > > 
> > > 
> > > I did so too, multiple times, with redis and mongo as well, tried serveral videos etc. - no such luck.
> > 
> > 
> > You version youtubei.js 10.4.0 ? See in server/packages.json And see server/node_modules/youtubei.js/packages.json first or two line "version: "10.4.0"
> 
> Yes, I checked both locations:
> 
> ```
> root@19a445b424e5:/home/app/server/node_modules/youtubei.js# cat package.json | grep version
>   "version": "10.4.0",
> ```
> 
> ```
> root@19a445b424e5:/home/app/server# cat package.json | grep youtube
>     "youtubei.js": "10.4.0",
> ```

This is strange, I also tried to do it in an already assembled docker container and it also worked.  I can't tell you why you have a problem, but I suspect something is still done wrong :(

The only thing that I see a difference between my own and your version is the length of the po_token, for some reason it is much longer than mine. In my case, the generator outputs a po_token in one line, in your case it is more than 3 lines long. Perhaps initially there is a problem with its generation?

**Comment by odd-orca** [comment]
> > > > > > You were right! Instance starts with the tokens but i stell get the error:
> > > > 
> > > > 
> > > > > > ![2024-09-28_11-00](https://private-user-images.githubusercontent.com/99789354/371744363-b05049ba-c2ab-4847-a13d-69db129410d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ1OTAsIm5iZiI6MTcyNzUxNDI5MCwicGF0aCI6Ii85OTc4OTM1NC8zNzE3NDQzNjMtYjA1MDQ5YmEtYzJhYi00ODQ3LWExM2QtNjlkYjEyOTQxMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA5MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNTU3MGZmNTdlZWJhZjM1NjA2ZmY3NTNmZWU1YTJhODVkMmQ2YzQ2N2RmMzdkYjM4MWJkYmJkZWY4ZWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMq6oa7sho7dlLt4CLT3wLLRBvq8Yzl1ALKzz3ev-bo)
> > > > 
> > > > 
> > > > > > But thanks anyway!
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > maybe something didn't assemble correctly? in my case it helped, but I had to completely restart the instance.
> > > > 
> > > > 
> > > > I did so too, multiple times, with redis and mongo as well, tried serveral videos etc. - no such luck.
> > > 
> > > 
> > > You version youtubei.js 10.4.0 ? See in server/packages.json And see server/node_modules/youtubei.js/packages.json first or two line "version: "10.4.0"
> > 
> > 
> > Yes, I checked both locations:
> > ```
> > root@19a445b424e5:/home/app/server/node_modules/youtubei.js# cat package.json | grep version
> >   "version": "10.4.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@19a445b424e5:/home/app/server# cat package.json | grep youtube
> >     "youtubei.js": "10.4.0",
> > ```
> 
> This is strange, I also tried to do it in an already assembled docker container and it also worked. I can't tell you why you have a problem, but I suspect something is still done wrong :(
> 
> The only thing that I see a difference between my own and your version is the length of the po_token, for some reason it is much longer than mine. In my case, the generator outputs a po_token in one line, in your case it is more than 3 lines long. Perhaps initially there is a problem with its generation?

Well I used the invidous script mentioned in the Docs - tried it serveral times, it always threw quite a long token.

On  the other hand, my invidious instance doesn't work with these tokens either - I had to comment the whole part out in my docker-compose file to make it work..

At least one instance is working as intended at the moment, so we'll see about the future updates and fixes.

Thanls again for your help!

**Comment by wes1993** [comment]
Hello all, 
I have the same problem, trying to use the dev branch I have this error:
```
viewtube-1          | Scheduled subscription job to run every 60 minutes
viewtube-1          |
viewtube-1          | /home/app/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/pluginUtils.js:125
viewtube-1          |     throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
viewtube-1          |           ^
viewtube-1          | FastifyError [Error]: fastify-plugin: @fastify/helmet - expected '5.x' fastify version, '4.28.1' is installed
viewtube-1          |     at Object.checkVersion (/home/app/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/pluginUtils.js:125:11)
viewtube-1          |     at Object.registerPlugin (/home/app/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/pluginUtils.js:148:16)
viewtube-1          |     at Boot.override (/home/app/node_modules/.pnpm/fastify@4.28.1/node_modules/fastify/lib/pluginOverride.js:28:57)
viewtube-1          |     at Boot._loadPlugin (/home/app/node_modules/.pnpm/avvio@8.3.2/node_modules/avvio/boot.js:425:25)
viewtube-1          |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
viewtube-1          |   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
viewtube-1          |   statusCode: 500
viewtube-1          | }
viewtube-1          |
viewtube-1          | Node.js v20.18.0
```

Could someone help me?

Best Regards
Stefano

**Comment by wouldntyouknow** [comment]
Just installed Viewtube, and have the same issue. The mentioned error after about 20 seconds of video playback.

**Comment by LordS4me** [comment]
Any news on this ?
